# Generated by Django 4.0 on 2022-01-21 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_djmalladdress_is_default_and_more'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='djmallorderinfo',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.djmalluser', verbose_name='用户'),
            preserve_default=False,
        ),
    ]
