# Generated by Django 3.2.9 on 2021-11-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djmallproductcategory',
            name='icon',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='product/category/icon/', verbose_name='分类图标'),
        ),
        migrations.AlterField(
            model_name='djmallproductcategory',
            name='pc_img',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='product/category/pc/img/', verbose_name='首页楼层背景'),
        ),
    ]
