# Generated by Django 3.2.9 on 2021-12-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211130_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djmallproductcategory',
            name='icon',
            field=models.ImageField(default=1, max_length=200, upload_to='product/category/icon/', verbose_name='分类图标'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='djmallproductcategory',
            name='pc_img',
            field=models.ImageField(default=1, max_length=200, upload_to='product/category/pc/img/', verbose_name='首页楼层背景'),
            preserve_default=False,
        ),
    ]
