# Generated by Django 3.2.9 on 2021-12-06 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20211201_0904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='djmallproductbrand',
            options={'ordering': ['-sort'], 'verbose_name': '商品品牌', 'verbose_name_plural': '商品品牌'},
        ),
        migrations.AlterModelOptions(
            name='djmallproductcarouse',
            options={'ordering': ['-sort'], 'verbose_name': '商品轮播图', 'verbose_name_plural': '商品轮播图'},
        ),
        migrations.AlterModelOptions(
            name='djmallproductcategory',
            options={'ordering': ['-sort'], 'verbose_name': '商品分类', 'verbose_name_plural': '商品分类'},
        ),
        migrations.AlterModelOptions(
            name='djmallproductsku',
            options={'ordering': ['-sort'], 'verbose_name': '商品SKU', 'verbose_name_plural': '商品SKU'},
        ),
        migrations.AlterModelOptions(
            name='djmallproductspu',
            options={'ordering': ['-sort'], 'verbose_name': '商品SPU', 'verbose_name_plural': '商品SPU'},
        ),
        migrations.AlterModelOptions(
            name='djmallproductspuspec',
            options={'ordering': ['-add_date'], 'verbose_name': '商品规格', 'verbose_name_plural': '商品规格'},
        ),
        migrations.AlterModelOptions(
            name='djmallproductspuspecoption',
            options={'ordering': ['-add_date'], 'verbose_name': '商品规格值', 'verbose_name_plural': '商品规格值'},
        ),
        migrations.AlterField(
            model_name='djmallproductbrand',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.djmallproductcategory', verbose_name='所属分类'),
        ),
        migrations.AlterField(
            model_name='djmallproductbrand',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='品牌描述'),
        ),
        migrations.AlterField(
            model_name='djmallproductbrand',
            name='name',
            field=models.CharField(max_length=50, verbose_name='品牌名称'),
        ),
        migrations.AlterField(
            model_name='djmallproductcategory',
            name='icon',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='product/category/icon/', verbose_name='分类图标'),
        ),
        migrations.AlterField(
            model_name='djmallproductcategory',
            name='pc_img',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='product/category/pc/img/', verbose_name='首页楼层背景'),
        ),
        migrations.AlterField(
            model_name='djmallproductsku',
            name='options',
            field=models.ManyToManyField(blank=True, to='product.DJMallProductSPUSpecOption', verbose_name='规格值'),
        ),
        migrations.AlterField(
            model_name='djmallproductspuspecoption',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.djmallproductspuspec', verbose_name='规格'),
        ),
    ]
