# Generated by Django 4.0 on 2021-12-23 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20211206_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djmallproductcategory',
            name='icon',
            field=models.ImageField(blank=True, help_text='大小为 96px * 96px', max_length=200, null=True, upload_to='product/category/icon/', verbose_name='分类图标'),
        ),
    ]
