# Generated by Django 4.0 on 2022-01-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_djmallshopingcart'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='djmallshopingcart',
            constraint=models.UniqueConstraint(fields=('owner', 'sku'), name='unique_owner_sku'),
        ),
    ]
