# Generated by Django 4.0 on 2021-12-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_djmallemailverifyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djmalluser',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='手机号'),
        ),
    ]
