# Generated by Django 4.0 on 2022-01-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_djmalluser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='djmalluser',
            name='address',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='默认收货地址'),
        ),
    ]
