# Generated by Django 4.0 on 2022-01-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_djmalluser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='djmalluser',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='个人简介'),
        ),
        migrations.AddField(
            model_name='djmalluser',
            name='nickename',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='昵称'),
        ),
        migrations.AddField(
            model_name='djmalluser',
            name='signa',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='个性签名'),
        ),
    ]
