# Generated by Django 4.0 on 2022-01-08 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0006_djmallfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='djmallfavorite',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.djmalluser', verbose_name='关联用户'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='djmallfavorite',
            unique_together={('owner', 'content_type', 'object_id')},
        ),
    ]
