# Generated by Django 4.0 on 2022-01-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_djmallfavorite_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='djmalluser',
            name='avatar',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='users/avatar/', verbose_name='头像'),
        ),
    ]
