# Generated by Django 4.0 on 2022-01-19 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_djmalladdress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djmalluser',
            name='address',
        ),
    ]
