# Generated by Django 4.0 on 2022-01-19 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_djmalluser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='djmalluser',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.djmalladdress', verbose_name='默认收货地址'),
        ),
    ]
