# Generated by Django 4.0 on 2022-01-19 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_djmalluser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djmalladdress',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.djmalluser', verbose_name='用户'),
        ),
    ]
