# Generated by Django 4.0 on 2022-01-20 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_djmalladdress_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djmalladdress',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='设为默认'),
        ),
        migrations.AlterField(
            model_name='djmalluser',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.djmalladdress', verbose_name='默认收货地址'),
        ),
    ]
